name: commit-tests

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - feature*
      - tech*
      - bugfix*
  pull_request:

jobs:
  commit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.44.0
        args: --verbose

    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Build
      run: go build -v ./...
    
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)

