name: Go

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - feature*
      - tech*
      - bugfix*
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.44.0
        args: --verbose
