name: golangci
on:
  push:
    tags:
      - v*
      - feature*
    branches:
      - master
      - main
  pull_request:
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.16.0]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.16.0’

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v  ./...