name: secondary-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  secondary-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
# To be Build